SUPABASE_URL = "https://mshwskpjursyhvxffqtb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zaHdza3BqdXJzeWh2eGZmcXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjU1NDIsImV4cCI6MjA3MDY0MTU0Mn0.3SlwBTxZzpxHqk29wf9FDnK9wNt9qYbWQTFmeM7YZJk"
SUPABASE_BUCKET = "task-files"
